#################################################
        ##MiWyf CP1 AM V1.0##
######### 20220709 by MiWyf #####################

# Your secrets.yaml
#  wifi_ssid: 'ssid'    #WiFi_SSID名称
#  wifi_password: '12345678'    #WiFi密码
#  wifi_password_AP: '12345678'  #ap_WiFi密码
#  wifi_fast_connect: 'false'   #如果SSID是隐藏的，设置为true
#  wifi_reboot_timeout: 60s  #WiFi离线多久后重启设备，秒s/分钟min/小时h，不需要此功能设置为0s
#  ota_password: '12345678'    #OTA密码
#  api_password: '12345678'    #OTA密码
#  api_reboot_timeout: 0s  #与客户端（如Home Assistant）失去连接多久后重启设备，秒s/分钟min/小时h，不需要此功能设置为0s
#  mqtt_reboot_timeout: 0s

#################################################

substitutions:
  #Name your Gateway
  device_name: miwyf-cp1-am
  #Home Assistant Name
  friendly_name: MiWyf CP1 AM
  #Secret YAML is used for next data:
  api_pw: !secret api_password
  ota_pw: !secret ota_password

#esphome:
#  name: ${device_name}
#  platform: ESP8266
#  board: esp01_1m
#  esp8266_restore_from_flash: true
#  #restore_from_flash: true
  
##new mode
esphome:
  name: ${device_name}
  #platformio_options:
    #platform: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
    #board_build.flash_mode: dio
esp8266:
  board: esp01_1m
  framework:
    version: recommended
  restore_from_flash: true
  #board_flash_mode: dio
  ##for switch false
  #early_pin_init: false
  
preferences:
  #flash_write_interval: 1min
  flash_write_interval: 3s

# Enable logging
#logger:
#  level: DEBUG

# Enable Home Assistant API
api:
  password: ${api_pw}
  reboot_timeout: 0s

# Enable OTA
ota:
  password: ${ota_pw}

#Enable WEB
web_server:
  port: 80

# Enable HA Time
time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: "12345678"

captive_portal:

status_led:
  pin:
    number: GPIO2
    inverted: yes

  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${friendly_name} Status"
#  - platform: gpio
#    pin: GPIO2
#    name: "${friendly_name} Sensor"


switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO13
    inverted: true
    id: relay
    on_turn_on:
      - switch.turn_off: ina
      - switch.turn_on: inb
      - delay: 100ms
      - switch.turn_off: ina
      - switch.turn_off: inb
      - delay: 100ms
    on_turn_off:
      - switch.turn_on: ina
      - switch.turn_off: inb
      - delay: 100ms
      - switch.turn_off: ina
      - switch.turn_off: inb
      - delay: 100ms
    
  - platform: gpio
    pin: GPIO5
    id: ina
  - platform: gpio
    pin: GPIO4
    id: inb
    
  - platform: template
    name: "${friendly_name} Energy Reset"
    icon: "mdi:switch"
    optimistic: true
    id: energy_reset
    #turn_off_action:
      #- sensor.integration.reset:  my_total_daily_energy 
    turn_on_action:
      - sensor.integration.reset: my_total_energy 
    
  - platform: restart
    name: "${friendly_name} Restart"

#UART Settings
uart:
  rx_pin: 14
  baud_rate: 4800
     
sensor:
  - platform: uptime
    id: uptime_s
    update_interval: 60s
  - platform: total_daily_energy
    id: my_total_daily_energy
    name: "${friendly_name} Total Daily Energy"
    power_id: my_power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: integration
    id: my_total_energy
    name: "${friendly_name} Total Energy" 
    sensor: my_power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    time_unit: h
    restore: true
    min_save_interval: 60s
  - platform: cse7766
    update_interval: 10s
    current:
      name: "${friendly_name} Current"
    voltage:
      name: "${friendly_name} Voltage"
    power:
      id: my_power
      name: "${friendly_name} Power"
      filters:
#        - sliding_window_moving_average:
#            window_size: 10
#            send_every: 10
#            send_first_at: 1
        - lambda: return x;
    energy:
      name: "${friendly_name} Energy"
      unit_of_measurement: kWh
      filters:
        - multiply: 0.001          
            
# Extra sensor to keep track of gateway uptime
text_sensor:
  - platform: template
    name: "${friendly_name} Uptime"
    lambda: |-
      uint32_t dur = id(uptime_s).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start
    update_interval: 60s

