# This is a basic workflow to help you get started with Actions

name: heox GitHub Actions Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 1. git checkout...
        uses: actions/checkout@v3

      - name: 2. setup nodejs...
        uses: actions/setup-node@v3
      
      - name: 3. install hexo...
        run: |
          npm install hexo-cli -g
          npm i -S hexo-prism-plugin -g
          npm install hexo-generator-search --save -g
          npm i hexo-permalink-pinyin  -g
          npm i --save hexo-wordcount -g
          npm install hexo-filter-github-emojis  -g
          npm install hexo-generator-feed  -g
          npm install

      - name: 4. hexo generate public files...
        run: |
          hexo clean
          hexo g
        
      # 提交到我们的存放静态资源的仓库
      - name: Build and Deploy

        uses: y4code/hexo-deploy-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_REPOSITORY: miwyf/miwyf.github.io # The repository the action should deploy to.
          BRANCH: master  # The branch the action should deploy to.
          PUBLISH_DIR: ./public # The folder the action should deploy.
